### ISSUE TITLE
Examine Contents select all can be confused.

### ISSUE THREAD

**Issue by Hwesta** [artefactual-labs/appraisal-tab#53]
Select all checkbox in examine contents can get confused. To reproduce:
- Select all with Select All checkbox
- Unselect one entry (Select All becomes unchecked)
- Click Select All checkbox
- Expected behavior: All rows selected
- Actual behavior: All rows unchecked, but select all is checked.

Note this doesn't happen with the file list pane's select all button.

**Comment by mistydemeo** [comment]
It looks like the `all_selected` binding isn't being updated in this circumstance; it's evaluating as false even if all boxes are checked.

**Comment by mistydemeo** [comment]
Looks like a secondary issue is scoping. The setters in the checklist brittly use `$scope.$parent.$parent`, however the exact level of parentage for the element depends on context. Loops, such as the ones used to populate the table, introduce new child scopes, and it's that inner scope in which the checklist is operating. The `all_selected` value exists in an upper scope, and the cause of this bug is that the value used by the "select all" button and by the individual checkboxes are different variables.
